tasks:
  - init: pyenv install 3.8.2 && pyenv global 3.8.2 && pip install -r requirements.txt
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==